version: 0.0
os: linux

files:
  - source: 
    destination: /home/ubuntu/AGame_MVP
    overwrite: yes

permissions:
  - object: /home/ubuntu/AGame_MVP
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    runas : ubuntu

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 500
      runas: root
