version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/AGame_MVP
    overwrite: true

permissions:
  - object: /home/ubuntu/AGame_MVP
    pattern: "**"
    runas : ubuntu

hooks:
  BeforeInstall:
    - location: cleanup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy.sh
      timeout: 500
      runas: root
