spring.application.name=MVP_AGame_SPRING

##dev purpose
#spring.security.user.name = demo1
#spring.security.user.password = 0000
#
## delete h2
#
## set to valid .
#spring.app.jwtSecret = mySecretKeyadfdsfasdfadfadfadfasdfasdfasdfasdfasdfasdfasdfasdf
#spring.app.jwtExpirationMs = 86400000

## Postgresql database
#spring.datasource.url = jdbc:postgresql://localhost:5432/a
#spring.datasource.username=postgres
#spring.datasource.password = 123456789

spring.jpa.hibernate.ddl-auto = update
#this is the dialect,
#spring.jpa.database-platgorm = org.hibernate.dialect.PostgreSQLDialect

#logging.level.org.springframework= DEBUG
#logging.level.org.hibernate.SQL=debug
#logging.level.org.springframework.security=debug
#logging.level.com.example.securitydemo=debug
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spotify.client.id = ${SPOTIFY_CLIENT_ID}
spotify.client.secret.id = ${SPOTIFY_SECRET_CLIENT_ID}

youtube.api.key =${YOUTUBE_API_KEY}

#>>>>>>> ccdf97dd344b298215360fdac2d2ed05393d10eb
spring.mvc.view.prefix=/static/
spring.mvc.view.suffix=.html
spring.web.resources.static-locations=classpath:/static/
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.web.resources.add-mappings=true
#spring.mvc.servlet.path=/api
# .env.development
spotify.redirectUri.dev=http://localhost:8080/api
frontend.redirectUri.dev=http://13.209.50.203:8080/dashboard

# .env.production
spotify.redirectUri = http://13.209.50.203:8080/api/spotify/callback
frontend.redirectUri=http://13.209.50.203:8080/dashboard
